language: perl
perl:
  - "5.28"
  - "5.26"
env: PGVERSION=system
script: perl -E 'say $ENV{PGVERSION}'
jobs:
  include:
    - { env: PGVERSION=11 }
    - { env: PGVERSION=10 }
    - { stage: Special }
