language: perl
perl:
  - "5.28"
  - "5.26"
env: PGVERSION=system
script: perl -E "say $ENV{PGVERSION}"
matrix:
  include:
    - perl: "5.28"
      env:
        - PGVERSION=11
    - perl: "5.28"
      env:
        - PGVERSION=10
